with open("src/app/pageViews.types.ts", "a") as f:
    f.write("\n")
    f.write("// Course accent colours, cycles through SA-themed palette\n")
    f.write("export const COURSE_COLOURS = [\n")
    f.write('  { bg: "#E8F5EE", accent: "#007A4D", light: "#C8EAD9" }, // green\n')
    f.write('  { bg: "#FFF8E7", accent: "#FFB612", light: "#FFE9A0" }, // gold\n')
    f.write('  { bg: "#FFF0EF", accent: "#E03C31", light: "#FCCFCC" }, // red\n')
    f.write('  { bg: "#EEF4FF", accent: "#3B7DD8", light: "#C5D9F7" }, // blue\n')
    f.write('  { bg: "#F3EEFF", accent: "#7C4DFF", light: "#D9C8FF" }, // purple\n')
    f.write('  { bg: "#E8FAF0", accent: "#00BFA5", light: "#B2EFE3" }, // teal\n')
    f.write('  { bg: "#FFF3E0", accent: "#F57C00", light: "#FFD9A8" }, // orange\n')
    f.write('  { bg: "#FCE4EC", accent: "#C2185B", light: "#F5B8CE" }, // pink\n')
    f.write("];\n")
    f.write("\n")
    f.write("export type SavedLessonProgress = {\n")
    f.write("  courseId: string;\n")
    f.write("  lessonId: string;\n")
    f.write("  lessonTitle?: string;\n")
    f.write("  completedAt: number; // timestamp\n")
    f.write("};\n")
